apiVersion: v1
kind: ConfigMap
metadata:
  name: game-demo
data:
  # file-like keys
  appsettings.region.json: |
    {
        "Logging": {
            "LogLevel": {
                "Default": "Information",
                "Microsoft": "Warning",
                "Microsoft.Hosting.Lifetime": "Information"
            }
        },
        "AllowedHosts": "*",
        "Region":  {{ .Values.Region | quote }}
    }