{{- define "connectionstringsecret" }}
{{- with .Values }}
{{- printf "{\"ConnectionString\":\"%s\"}" .connectionstring | b64enc }}
{{- end }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: application-secret
data:
  # file-like keys
  appsettings.region.json: |
    {{ template "connectionstringsecret" . }}
